name: Tự động Deploy lên Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Tải source code về server
        uses: actions/checkout@v4

      - name: Cài đặt Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cài đặt dependencies
        run: npm ci

      - name: Build Tailwind CSS
        run: npx @tailwindcss/cli -i src/input.css -o public/styles.css --minify

      - name: Cài đặt Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy lên Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SA }}' # <-- ĐỔI THÀNH TÊN NÀY CHO KHỚP
          projectId: farmi-go
          channelId: live
